trigger:
  branches:
    include:
      - main

pool:
  vmImage: 'ubuntu-latest'

steps:
  # Clone the GitHub repository and initialize Terraform, plan, and apply in one script
  - checkout: self
    persistCredentials: true

  - task: TerraformInstaller@0
    inputs:
      terraformVersion: '1.5.0'

  - script: |
      git clone https://github.com/AnandJoy7/TF-S3-Task.git
      cd TF-S3-Task
      terraform init
      terraform plan
      terraform apply -auto-approve
    displayName: 'Clone Git Repo, Terraform Init, Plan, and Apply'
    env:
      AWS_ACCESS_KEY_ID: $(AWS_ACCESS_KEY_ID)
      AWS_SECRET_ACCESS_KEY: $(AWS_SECRET_ACCESS_KEY)
      AWS_REGION: 'us-east-1'  # Replace with your desired AWS region
